name: Workflow for Maven using Snyk 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven-3-jdk-11@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: --json-file-output=test.json
    - run: ls -la
      if: ${{ always() }}
  custom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
    - name: Snyk requires Maven to have downloaded the dependencies before running
      run: mvn install --no-transfer-progress
    - name: Run vulnerability check action
      uses: thehyve/vulnerability-check-action@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        file: 'pom.xml'
        organisation: 'thehyve'
